[package]
name = "vault-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.vault]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../../../dharitri-wasm-debug"
