[package]
name = "parent-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.parent]
path = ".."

[dependencies.dharitri-wasm]
version = "0.10.8"
path = "../../../../../../dharitri-wasm"

[dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../../../../dharitri-wasm-debug"
