[package]
name = "pair-meta"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[dependencies.order-book-pair]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../../../dharitri-wasm-debug"
