[package]
name = "kitty-auction"
version = "0.0.0"
authors = [ "dorin-iancu <dorin.iancu@dharitri.com>",]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.kitty]
version = "0.0.0"
path = "../common/kitty"

[dependencies.kitty-ownership]
version = "0.0.0"
path = "../kitty-ownership"

[dependencies.dharitri-wasm]
version = "0.10.8"
path = "../../../../dharitri-wasm"

[dev-dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../../dharitri-wasm-debug"
