[package]
name = "digital-cash-wasm"
version = "0.0.0"
authors = ["Valentin Craciun"]
edition = "2021"
publish = false

[lib]
crate-type = [ "cdylib",]

[workspace]
members = [ ".",]

[dev-dependencies]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"

[dependencies.digital-cash]
path = ".."

[dependencies.dharitri-wasm-node]
version = "0.10.8"
path = "../../../../dharitri-wasm-node"

[dependencies.dharitri-wasm-output]
version = "0.10.8"
features = ["wasm-output-mode"]
path = "../../../../dharitri-wasm-output"
