[package]
name = "order-book-pair"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-wasm]
version = "0.10.8"
path = "../../../../dharitri-wasm"
features = ["alloc"]
