[package]
name = "send-tx-repeat-wasm"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@dharitri.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"

[dependencies.send-tx-repeat]
path = ".."

[dependencies.dharitri-wasm-node]
version = "0.10.8"
path = "../../../../dharitri-wasm-node"

[dependencies.dharitri-wasm-output]
version = "0.10.8"
path = "../../../../dharitri-wasm-output"
features = ["wasm-output-mode"]

[workspace]
members = ["."]
