[package]
name = "kitty-genetic-alg-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.kitty-genetic-alg]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../../../dharitri-wasm-debug"
