[package]
name = "proxy-pause"
version = "0.0.0"
authors = [ "you",]
edition = "2021"
publish = false

[lib]
path = "src/proxy_pause.rs"

[dependencies.dharitri-wasm]
version = "0.10.8"
path = "../../../dharitri-wasm"

[dependencies.dharitri-wasm-modules]
version = "0.10.8"
path = "../../../dharitri-wasm-modules"

[dev-dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../dharitri-wasm-debug"

[dev-dependencies.use-module]
path = "../../feature-tests/use-module"
