[package]
name = "str-repeat-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.str-repeat]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../dharitri-wasm-debug"
