[package]
name = "formatted-message-features-wasm"
version = "0.0.0"
authors = [ "you",]
edition = "2021"
publish = false

[lib]
crate-type = [ "cdylib",]

[workspace]
members = [ ".",]

[dev-dependencies]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"

[dependencies.formatted-message-features]
path = ".."

[dependencies.dharitri-wasm-node]
version = "0.10.8"
path = "../../../../dharitri-wasm-node"

[dependencies.dharitri-wasm-output]
version = "0.10.8"
path = "../../../../dharitri-wasm-output"
features = [ "wasm-output-mode",]
