[package]
name = "big-float-features"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2021"
publish = false

[lib]
path = "src/big_float_main.rs"

[dependencies.dharitri-wasm]
version = "0.10.8"
path = "../../../dharitri-wasm"
features = ["big-float"]

[dev-dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../dharitri-wasm-debug"

[dependencies.dharitri-wasm-modules]
version = "0.10.8"
path = "../../../dharitri-wasm-modules"

[dev-dependencies.dct-system-sc-mock]
path = "../dct-system-sc-mock"
