[package]
name = "local-dct-and-nft-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.local-dct-and-nft]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.38.0"
path = "../../../../../dharitri-wasm-debug"
