[package]
name = "queue-repeat-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.queue-repeat]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../../../dharitri-wasm-debug"
