[package]
name = "crowdfunding-dct-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.crowdfunding-dct]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../../dharitri-wasm-debug"
