[package]
name = "promises-features-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.promises-features]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.10.8"
path = "../../../../../dharitri-wasm-debug"
